### PR TITLE
Specify go1.19 for the builder stage in Dockerfile

### LINKED ISSUE #32: Dockerfile fails to build because quic-go is incompatible with the latest Go version
The current Dockerfile build is failing because ~~it's attempting to build with Go 1.20.~~ quic-go is not yet compatible with Go 1.20.

### PR DESCRIPTION
**Pull request by RobotSail**
Fixes #32 
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

### CODE REVIEW

**Comment by marten-seemann** [comment]
Why would we use a Go version that’s officially outdated and unsupported?

**Comment by RobotSail** [comment]
@marten-seemann If you try building with the current image, it breaks because the version of `lucas-clemente/quic-go` we're using is not compatible or ready for go1.20 yet:
```
#9 11.33 /go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.0/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```
I hadn't tried to upgrade that package or seeing if a compatible version was available, and was hoping to instead contribute this as a quick fix to get a build for my own purposes. I can bump this PR to go1.19 or just keep it gated until a compatible version is released. 

Looking at the `go.mod` for that package, it looks like it's [still on go1.18](https://github.com/quic-go/quic-go/blob/5b72f4c900f209b5705bb0959399d59e495a2c6e/go.mod#L3).

**Comment by marten-seemann** [comment]
The version in go.mod is the **minimum** version. Why not use 1.19?

**Comment by RobotSail** [comment]
@marten-seemann Updated it to use Go1.19.

**Comment by RobotSail** [comment]
I'm seeing that quic-go does actually support Go 1.20 as of release v0.32.0 thanks to your PR. Going to update the dependencies for this project so that it can smoothly use the latest Golang build rather than relying on an older version.

**Comment by RobotSail** [comment]
It looks like quic-go is locked into release `v0.31.0` because of it being a dependency for `go-libp2p`:
```
➜ grep lucas-clemente/quic-go go.mod
	github.com/lucas-clemente/quic-go v0.31.1 // indirect
➜ go mod why github.com/lucas-clemente/quic-go
# github.com/lucas-clemente/quic-go
github.com/libp2p/go-libp2p-relay-daemon/cmd/libp2p-relay-daemon
github.com/libp2p/go-libp2p
github.com/libp2p/go-libp2p/config
github.com/lucas-clemente/quic-go
```

**Comment by RobotSail** [comment]
I've created a PR for the issue in go-libp2p here: https://github.com/libp2p/go-libp2p/pull/2061

**Review by marten-seemann — APPROVED** [review]

**Pull request merged**
